import streamlit as st

st.markdown(
    """
# About "Banana Pencil Club"
This is a simple app for generating stories using AI for kids.
With a few quick entries about your protagonist and story premise, you can generate a complete story with images.
You can upload an image of yourself or your child to be the hero of the story or savior of the day!

This app is a hackathon project built in 48 hours.

It uses:
- [Nano Banana](https://blog.google/products/gemini/updated-image-editing-model/) for image generation
- [Gemini 2.5 Flash](https://blog.google/products/gemini/introducing-gemini-2-5-flash/) for text generation
- [Streamlit](https://streamlit.io/) for the web app
- [PIL](https://github.com/python-pillow/Pillow) for image processing
- [Pydantic](https://docs.pydantic.dev/latest/) for data validation
- [St Page Flip](https://nodlik.github.io/StPageFlip/) for the flipbook component


Built by [Akash Patki](https://keycache.github.io/)

## Disclaimer
This app is for demonstration purposes only. The generated stories and images may not be suitable for all audiences.
Please use discretion when sharing the generated content with children.

* The stories generated within a session are available only for the duration of that session and are not stored permanently.
* The content generated by the app is created by AI models and is not moderated. Please review the content before sharing it with children.
* This app is just a fun project and is not intended for commercial use or distribution.

"""
)
